---
Name: frontendlivingdocroutes
After: 'framework/routes#coreroutes'
---
Director:
  rules:
    'FrontendInsertDialog': 'FrontendInsertDialog'
    'render-shortcode': 'ShortcodeRenderer'
#    'lf-workflow': 'FwController'